/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ISupraOraclePull {
  export type PriceDataStruct = {
    pairs: BigNumberish[];
    prices: BigNumberish[];
    decimals: BigNumberish[];
  };

  export type PriceDataStructOutput = [
    pairs: bigint[],
    prices: bigint[],
    decimals: bigint[]
  ] & { pairs: bigint[]; prices: bigint[]; decimals: bigint[] };
}

export interface ISupraOraclePullInterface extends Interface {
  getFunction(nameOrSignature: "verifyOracleProof"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyOracleProof",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyOracleProof",
    data: BytesLike
  ): Result;
}

export interface ISupraOraclePull extends BaseContract {
  connect(runner?: ContractRunner | null): ISupraOraclePull;
  waitForDeployment(): Promise<this>;

  interface: ISupraOraclePullInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyOracleProof: TypedContractMethod<
    [_bytesproof: BytesLike],
    [ISupraOraclePull.PriceDataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyOracleProof"
  ): TypedContractMethod<
    [_bytesproof: BytesLike],
    [ISupraOraclePull.PriceDataStructOutput],
    "nonpayable"
  >;

  filters: {};
}
