/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockOracleClientInterface extends Interface {
  getFunction(
    nameOrSignature: "deliverPriceData" | "updatePullAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deliverPriceData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePullAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deliverPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePullAddress",
    data: BytesLike
  ): Result;
}

export interface MockOracleClient extends BaseContract {
  connect(runner?: ContractRunner | null): MockOracleClient;
  waitForDeployment(): Promise<this>;

  interface: MockOracleClientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deliverPriceData: TypedContractMethod<
    [_bytesProof: BytesLike],
    [void],
    "nonpayable"
  >;

  updatePullAddress: TypedContractMethod<
    [oracle_: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deliverPriceData"
  ): TypedContractMethod<[_bytesProof: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePullAddress"
  ): TypedContractMethod<[oracle_: AddressLike], [void], "nonpayable">;

  filters: {};
}
